In [1]:
# Use Multilinear regression for predicting

In [39]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import random 
import matplotlib.pyplot as plt
import numpy as np

In [3]:
nfl_stats_salary = pd.read_csv(r'C:\Users\nlpru\Desktop\Personal\NFL Salary Project\NFL Project CSV\nfl_stats_salary.csv')

In [40]:
np.abs(nfl_stats_salary.corr()['Salary']).sort_values(ascending = False)

Salary    1.000000
Age       0.530905
Y/G       0.361882
Cmp       0.352923
Int%      0.347880
1D        0.297300
Yds       0.292905
Cmp%      0.287494
Wins      0.274263
Att       0.272904
GS        0.263488
ANY/A     0.221813
Rate      0.213428
AY/A      0.199353
Sk%       0.195569
4QC       0.182168
Int       0.178437
TD        0.163794
NY/A      0.158714
G         0.145228
GWD       0.133974
Y/A       0.119485
Losses    0.074194
Ties      0.072026
TD%       0.067254
Yds.1     0.066171
Lng       0.062365
Y/C       0.037990
Sk        0.011670
Name: Salary, dtype: float64

In [42]:
features = ['Y/G', 'Cmp','Int%','1D','Yds']

In [43]:
X = nfl_stats_salary.loc[:,features].values
Y = nfl_stats_salary.loc[:,'Salary'].values

In [17]:
nfl_stats_salary['Salary'].corr(nfl_stats_salary['GWD'])

0.13397393147029815

In [44]:
regression = LinearRegression().fit(X,Y)

In [45]:
regression.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': False}

In [50]:
X_test = nfl_stats_salary.loc[:5,features]
Y_test = nfl_stats_salary.loc[:5, ['Salary']]

In [51]:
prediction = regression.predict(X_test)

In [53]:
Y_test.values.flatten()

array([33500000,  6337819, 30000000, 23000000, 32000000,   680848],
      dtype=int64)

In [54]:
prediction - Y_test.values.flatten()

array([-13800066.38521113,   -327143.83564667,  -4233630.57291451,
          594305.83414178,  -7058211.6788565 ,  20861536.19166033])

In [64]:
regression.coef_

array([  834661.68074925, -4381710.16551713,   115378.43012591,
        -211735.66998721])

In [65]:
nfl_stats_salary.loc[0,features]

Y/G     289.9
Cmp       394
Int%      2.6
1D        220
Yds      4638
Name: 0, dtype: object

In [67]:
regression.predict(np.array([289.9,394,2.6,220,4638]).reshape(1,-1))

array([19699933.61478887])

In [63]:
features

['Y/G', 'Cmp', 'Int%', '1D', 'Yds']